using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;

namespace Service
{
    public class EmailService
    {
        //public ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2010_SP1);

        //private string emailHost = "10.96.118.60";
        private string emailHost = "zmail.12345.com";
        //private string emailPort = "25";
        private string emailPort = "587";
        //private string senderAddress = "SSR.Alerts@12345.com";
        //private string password = "#$2022ERsr!!";
        private string senderAddress = "AP-itsm@12345.com";
        private string password = "ER@#2038inv";
        public EmailService()
        {
            //service.Credentials = new System.Net.NetworkCredential("alert@laugfs.lk", "n0TIfy@@6444");
            //service.UseDefaultCredentials = false;
            //System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

            //service.Url = new Uri("https://outlook.office365.com/ews/exchange.asmx");
            //service.TraceEnabled = true;
            //service.Timeout = 1000000;
        }
        public String SendEmail(List<string> ToRecipients, List<string> CCRecipients, String Subject, String EmailBody)
        {
            string systemName = GlobalStaticService.GetSystemName();
            String emailHeader = "";
            String emailFooter = "";

            string colorPrimary = "#007BFF";

            emailHeader += "<html><head></head><body> <div> <div itemscope='' itemtype='http://schema.org/EmailMessage'></div>";
            emailHeader += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; font-weight:normal!important; border-collapse:collapse!important'><tbody> ";
            emailHeader += "<tr><td bgcolor='#182643' align='center' style='font-weight:normal!important'>";
            emailHeader += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; font-weight:normal!important; border-collapse:collapse!important;'>";
            emailHeader += "<tbody> <tr> <td align='center' valign='top' style='font-weight:normal!important; padding: 5px 10px 5px 10px'></td> ";
            emailHeader += " </tr></tbody></table> </td> </tr>";
            emailHeader += "<tr>  <td bgcolor='" + colorPrimary + "' align='center' style='padding:0px 30px 0px 30px'>";
            emailHeader += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; border-collapse:collapse!important; width:98%;'>";
            emailHeader += "<tbody> <tr> <td bgcolor='#ffffff' align='center' valign='top' style='padding: 0px 0px 0px 0px;color: " + colorPrimary + ";'>";
            emailHeader += "<h1 style='color: #fff;font-family:Helvetica,Arial,sans-serif;letter-spacing:normal;margin:0px 0px 10px;padding:10px;display:block;font-style:normal;line-height:100%;font-size: 22px;font-weight:400;margin:0;text-align:center;line-height:40px;background:"+ colorPrimary + ";'>";
            emailHeader += " "+ systemName + " </h1>";

            emailHeader += " </td> </tr> </tbody></table> </td> </tr>";
            emailHeader += "<tr>  <td align='center' style='font-weight:normal!important;padding: 0px 30px 0px 30px'>";
            emailHeader += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; font-weight:normal!important; border-collapse:collapse!important; width:98% '>";
            emailHeader += " <tbody> <tr><td bgcolor='#ffffff' align='left' style='font-weight:normal!important; padding:20px 00px 40px 00px; color:#666666; font-family:'Lato',Helvetica,Arial,sans-serif; font-size:15px; font-weight:400; line-height:25px'>";

            emailFooter += " </td> </tr></tbody> </table> </td> </tr>";
            emailFooter += "<tr><td bgcolor='#f4f4f4' align='center' style='font-weight:normal!important; padding:0px 10px 0px 10px'>";
            emailFooter += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; font-weight:normal!important; border-collapse:collapse!important; color:#666666; font-family:'Lato',Helvetica,Arial,sans-serif;  font-weight:400;'>";
            emailFooter += " <tbody> <tr><td bgcolor='#f4f4f4' align='center' style='font-weight:normal!important; padding:0px 30px 30px 30px; line-height:15px;'>";
            emailFooter += "<br /> <p style='font-weight:bold!important; font-size:13px;'>This e-mail was generated by <a href='"+GlobalStaticService.GetAppUrl()+"'>"+ systemName + "</a>. </p>";
            emailFooter += " <p style='font-size:11px;'>"+DateTime.Today.Year.ToString()+"  All rights reserved.</p>";
            emailFooter += "</td></tr></tbody></table></td> </tr>";
            emailFooter += " </tbody></table> </div></body></html>";

            try
            {


                MailMessage mail = new MailMessage();
                mail.From = new MailAddress(senderAddress, systemName );
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient(emailHost, Convert.ToInt16(emailPort));
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;
                smtp.EnableSsl = true;
                //string pw = main_bl_common.Decrypt(dtSender.Rows[0]["email_smtp_password"].ToString(), encript_type);

                System.Net.NetworkCredential SMTPUserInfor = new System.Net.NetworkCredential(senderAddress,password);
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = SMTPUserInfor;

                try
                {
                    foreach (string recipients in ToRecipients)
                    {
                        mail.To.Add(recipients);
                    }
                }
                catch (Exception ex) { }
                try
                {
                    foreach (string recipients in CCRecipients)
                    {
                        mail.CC.Add(recipients);
                    }
                }
                catch (Exception ex) { }

                mail.Subject = Subject;
                mail.Body = emailHeader + EmailBody + emailFooter;

                // mail.To.Add("viraga.hiripitiya@12345.com");

                smtp.Send(mail);


                return "OK";

            }
            catch (Exception ex)
            {
                return ex.Message.ToString();
            }

        }

        public String SendEmailPublic(List<string> ToRecipients, List<string> CCRecipients, List<string> BCCRecipients, String Subject, String EmailBody)
        {
            string systemName = GlobalStaticService.GetSystemName();
            String emailHeader = "";
            String emailFooter = "";

            emailHeader += "<html><head></head><body> <div> <div itemscope='' itemtype='http://schema.org/EmailMessage'></div>";
            emailHeader += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; font-weight:normal!important; border-collapse:collapse!important'><tbody> ";
            emailHeader += "<tr><td bgcolor='#182643' align='center' style='font-weight:normal!important'>";
            emailHeader += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; font-weight:normal!important; border-collapse:collapse!important;'>";
            emailHeader += "<tbody> <tr> <td align='center' valign='top' style='font-weight:normal!important; padding: 5px 10px 5px 10px'></td> ";
            emailHeader += " </tr></tbody></table> </td> </tr>";
            emailHeader += "<tr>  <td bgcolor='#dd4b39' align='center' style='padding:0px 30px 0px 30px'>";
            emailHeader += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; border-collapse:collapse!important; width:98%;'>";
            emailHeader += "<tbody> <tr> <td bgcolor='#ffffff' align='center' valign='top' style='padding: 0px 0px 0px 0px;color: #dd4b39;'>";
            emailHeader += "<h1 style='color: #fff;font-family:Helvetica,Arial,sans-serif;letter-spacing:normal;margin:0px 0px 10px;padding:10px;display:block;font-style:normal;line-height:100%;font-size: 22px;font-weight:400;margin:0;text-align:center;line-height:40px;background:#dd4b39;'>";
            emailHeader += " " + systemName + " </h1>";

            emailHeader += " </td> </tr> </tbody></table> </td> </tr>";
            emailHeader += "<tr>  <td align='center' style='font-weight:normal!important;padding: 0px 30px 0px 30px'>";
            emailHeader += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; font-weight:normal!important; border-collapse:collapse!important; width:98% '>";
            emailHeader += " <tbody> <tr><td bgcolor='#ffffff' align='left' style='font-weight:normal!important; padding:20px 00px 40px 00px; color:#666666; font-family:'Lato',Helvetica,Arial,sans-serif; font-size:15px; font-weight:400; line-height:25px'>";

            emailFooter += " </td> </tr></tbody> </table> </td> </tr>";
            emailFooter += "<tr><td bgcolor='#f4f4f4' align='center' style='font-weight:normal!important; padding:0px 10px 0px 10px'>";
            emailFooter += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; font-weight:normal!important; border-collapse:collapse!important; color:#666666; font-family:'Lato',Helvetica,Arial,sans-serif;  font-weight:400;'>";
            emailFooter += " <tbody> <tr><td bgcolor='#f4f4f4' align='center' style='font-weight:normal!important; padding:0px 30px 30px 30px; line-height:15px;'>";
            emailFooter += "<br /> <p style='font-weight:bold!important; font-size:13px;'>This e-mail was generated by " + systemName + ". </p>";
            emailFooter += " <p style='font-size:11px;'>" + DateTime.Today.Year.ToString() + "  All rights reserved.</p>";
            emailFooter += "</td></tr></tbody></table></td> </tr>";
            emailFooter += " </tbody></table> </div></body></html>";

            try
            {


                MailMessage mail = new MailMessage();
                mail.From = new MailAddress(senderAddress, systemName);
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient(emailHost, Convert.ToInt16(emailPort));
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;
                smtp.EnableSsl = true;
                //string pw = main_bl_common.Decrypt(dtSender.Rows[0]["email_smtp_password"].ToString(), encript_type);

                System.Net.NetworkCredential SMTPUserInfor = new System.Net.NetworkCredential(senderAddress, password);
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = SMTPUserInfor;

                try
                {
                    foreach (string recipients in ToRecipients)
                    {
                        mail.To.Add(recipients);
                    }
                }
                catch (Exception ex) { }
                try
                {
                    foreach (string recipients in CCRecipients)
                    {
                        mail.CC.Add(recipients);
                    }
                }
                catch (Exception ex) { }

                mail.Subject = Subject;
                mail.Body = emailHeader + EmailBody + emailFooter;

                // mail.To.Add("viraga.hiripitiya@12345.com");

                smtp.Send(mail);


                return "OK";

            }
            catch (Exception ex)
            {
                return ex.Message.ToString();
            }

        }
        public String SendEmailScheduled(List<string> ToRecipients, List<string> CCRecipients, List<string> BCCRecipients, String Subject, String EmailBody)
        {
            string systemName = GlobalStaticService.GetSystemName();
            String emailHeader = "";
            String emailFooter = "";

            emailHeader += "<html><head></head><body> <div> <div itemscope='' itemtype='http://schema.org/EmailMessage'></div>";
            emailHeader += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; font-weight:normal!important; border-collapse:collapse!important'><tbody> ";
            emailHeader += "<tr><td bgcolor='#182643' align='center' style='font-weight:normal!important'>";
            emailHeader += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; font-weight:normal!important; border-collapse:collapse!important;'>";
            emailHeader += "<tbody> <tr> <td align='center' valign='top' style='font-weight:normal!important; padding: 5px 10px 5px 10px'></td> ";
            emailHeader += " </tr></tbody></table> </td> </tr>";
            emailHeader += "<tr>  <td bgcolor='#dd4b39' align='center' style='padding:0px 30px 0px 30px'>";
            emailHeader += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; border-collapse:collapse!important; width:98%;'>";
            emailHeader += "<tbody> <tr> <td bgcolor='#ffffff' align='center' valign='top' style='padding: 0px 0px 0px 0px;color: #dd4b39;'>";
            emailHeader += "<h1 style='color: #fff;font-family:Helvetica,Arial,sans-serif;letter-spacing:normal;margin:0px 0px 10px;padding:10px;display:block;font-style:normal;line-height:100%;font-size: 22px;font-weight:400;margin:0;text-align:center;line-height:40px;background:#dd4b39;'>";
            emailHeader += " " + systemName + " </h1>";

            emailHeader += " </td> </tr> </tbody></table> </td> </tr>";
            emailHeader += "<tr>  <td align='center' style='font-weight:normal!important;padding: 0px 30px 0px 30px'>";
            emailHeader += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; font-weight:normal!important; border-collapse:collapse!important; width:98% '>";
            emailHeader += " <tbody> <tr><td bgcolor='#ffffff' align='left' style='font-weight:normal!important; padding:20px 00px 40px 00px; color:#666666; font-family:'Lato',Helvetica,Arial,sans-serif; font-size:15px; font-weight:400; line-height:25px'>";

            emailFooter += " </td> </tr></tbody> </table> </td> </tr>";
            emailFooter += "<tr><td bgcolor='#f4f4f4' align='center' style='font-weight:normal!important; padding:0px 10px 0px 10px'>";
            emailFooter += "<table border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse:collapse; font-weight:normal!important; border-collapse:collapse!important; color:#666666; font-family:'Lato',Helvetica,Arial,sans-serif;  font-weight:400;'>";
            emailFooter += " <tbody> <tr><td bgcolor='#f4f4f4' align='center' style='font-weight:normal!important; padding:0px 30px 30px 30px; line-height:15px;'>";
            emailFooter += "<br /> <p style='font-weight:bold!important; font-size:13px;'>This e-mail was generated by <a href='" + GlobalStaticService.GetAppUrl() + "'>" + systemName + "</a>. </p>";
            emailFooter += " <p style='font-size:11px;'>" + DateTime.Today.Year.ToString() + "  All rights reserved.</p>";
            emailFooter += "</td></tr></tbody></table></td> </tr>";
            emailFooter += " </tbody></table> </div></body></html>";

            try
            {

                MailMessage mail = new MailMessage();
                mail.From = new MailAddress(senderAddress, systemName);
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient(emailHost, Convert.ToInt16(emailPort));
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11;
                smtp.EnableSsl = true;

                System.Net.NetworkCredential SMTPUserInfor = new System.Net.NetworkCredential(senderAddress, password);
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = SMTPUserInfor;

                try
                {
                    foreach (string recipients in ToRecipients)
                    {
                        mail.To.Add(recipients);
                    }
                }
                catch (Exception ex) { }
                try
                {
                    foreach (string recipients in CCRecipients)
                    {
                        mail.CC.Add(recipients);
                    }
                }
                catch (Exception ex) { }

                try
                {
                    foreach (string recipients in BCCRecipients)
                    {
                        mail.Bcc.Add(recipients);
                    }
                }
                catch (Exception ex) { }

                mail.Subject = Subject;
                mail.Body = emailHeader + EmailBody + emailFooter;

                smtp.Send(mail);

                return "OK";

            }
            catch (Exception ex)
            {
                return ex.Message.ToString();
            }

        }



    }
}