using DocumentFormat.OpenXml.Office2016.Excel;
using Domain;
using Domain.AR;
using Domain.CM;
using Domain.IM;
using Domain.RA;
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Web.Models;

namespace Web.Utility
{
    public class EmailTemplate
    {

        public String TicketCreate(string requestedUserName, Ticket ticket, RequestType requestType)
        {
            String Body = "<br><b>Dear " + requestedUserName + ",</b><br><br>";
            Body += "We would like to acknowledge that we have received your request (<b>" + requestType.TicketType.EnumDisplayName() + "</b>)";
            Body += " and a ticket has been created.<br>";
            Body += "A support representative will be reviewing your " + requestType.TicketType.EnumDisplayName() + " and will send you a response within 24 hours.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Ticket # </b>: " + ticket.Code;
            Body += "<br>";
            Body += "<b>Subject </b>: " + ticket.Subject;
            Body += "<br>";
            Body += "<b>Category </b>: " + requestType.Category.CategoryName;
            Body += "<br>";
            Body += "<b>Asset Type </b>: " + requestType.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Subcategory </b>: " + requestType.SubCategory.SubCategoryName;
            Body += "<br><br> Thank you! ";
            // Body += "<br><br><i><b>This email was generated by " + ResourceData.AppNameWithCode + "</b></i>";
            return Body;

        }



        public String TicketCreateTeam(string requestedUserName, Ticket ticket, RequestType requestType)
        {
            String Body = "<br><b>Dear " + requestedUserName + " Team ,</b><br><br>";
            Body += "New ticket has been assigned to your team. Please pay your attention.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Ticket # </b>: " + ticket.Code;
            Body += "<br>";
            Body += "<b>Subject </b>: " + ticket.Subject;
            Body += "<br>";
            Body += "<b>Category </b>: " + requestType.Category.CategoryName;
            Body += "<br>";
            Body += "<b>Asset Type </b>: " + requestType.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Subcategory </b>: " + requestType.SubCategory.SubCategoryName;
            Body += "<br><br> Thank you! ";
            //Body += "<br><br><i><b>This email was generated by " + ResourceData.AppNameWithCode + "</b></i>";
            return Body;

        }


        public String TicketAssigned(string receiver, Ticket ticket, RequestType requestType)
        {
            String Body = "<br><b>Dear " + receiver + ",</b><br><br>";
            Body += "New ticket has been assigned to you. Please attend to the same & complete the ticket.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Ticket # </b>: " + ticket.Code;
            Body += "<br>";
            Body += "<b>Subject </b>: " + ticket.Subject;
            Body += "<br>";
            Body += "<b>Category </b>: " + requestType.Category.CategoryName;
            Body += "<br>";
            Body += "<b>Asset Type </b>: " + requestType.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Subcategory </b>: " + requestType.SubCategory.SubCategoryName;

            Body += "<br><br> Thank you! ";
            //Body += "<br><br><i><b>This email was generated by " + ResourceData.AppNameWithCode + "</b></i>";
            return Body;

        }


        public String TicketTransfer(string requestedUserName, Ticket ticket, RequestType requestType)
        {
            String Body = "<br><b>Dear " + requestedUserName + " Team ,</b><br><br>";
            Body += "New ticket has been transferred to your team. Please pay your attention.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Ticket # </b>: " + ticket.Code;
            Body += "<br>";
            Body += "<b>Subject </b>: " + ticket.Subject;
            Body += "<br>";
            Body += "<b>Category </b>: " + requestType.Category.CategoryName;
            Body += "<br>";
            Body += "<b>Asset Type </b>: " + requestType.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Subcategory </b>: " + requestType.SubCategory.SubCategoryName;
            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String TaskCreated(string receiver, TicketTask ticketTask)
        {
            String Body = "<br><b>Dear " + receiver + " Team,</b><br><br>";
            Body += "New task has been assigned to your team. Please pay your attention.";
            //Body += "New task has been assigned to your team. Please attend to the same & complete the ticket.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Task </b>: " + ticketTask.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + ticketTask.Description;
            Body += "<br><br> Thank you! ";
            //Body += "<br><br><i><b>This email was generated by " + ResourceData.AppNameWithCode + "</b></i>";
            return Body;

        }

        public String TaskAssigned(string receiver, TicketTask ticketTask)
        {
            String Body = "<br><b>Dear " + receiver + ",</b><br><br>";
            Body += "New task has been assigned to you. Please attend to the same & complete the task.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Task </b>: " + ticketTask.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + ticketTask.Description;

            Body += "<br><br> Thank you! ";
            //Body += "<br><br><i><b>This email was generated by " + ResourceData.AppNameWithCode + "</b></i>";
            return Body;

        }
        public String TicketUpdate(string requestedUserName, string ticketCode, string status, string comment)
        {
            String Body = "<br><b>Dear " + requestedUserName + ",</b><br><br>";
            Body += "We are writing to inform you that there has been a recent update regarding your support ticket.";
            //Body += "There is a new comment on your ticket. You can view your ticket by visiting <a href='" + ResourceData.WebSiteURL.ToString() + "'>" + ResourceData.AppNameWithCode + " </a>.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Ticket # </b>: " + ticketCode;
            Body += "<br>";
            Body += "<b>Status </b>: " + status;
            Body += "<br>";
            Body += "<b>Comment </b>: " + comment;
            Body += "<br>";
            Body += "<br><br> Thank you! ";
            //Body += "<br><br><i><b>This email was generated by " + ResourceData.AppNameWithCode + "</b></i>";
            return Body;

        }

        public String TicketComplete(string requestedUserName, Ticket ticket)
        {
            String Body = "<br><b>Dear " + requestedUserName + ",</b><br><br>";
            Body += "Your ticket " + ticket.Code + " has been resolved. Please check & close the ticket. We hope that the ticket was resolved to your satisfaction. ";
            Body += "<br><br>If you feel that the ticket should not be closed or if the ticket has not been resolved, please reopen the ticket.";
            Body += "<br><br> Thank you! ";
            //Body += "<br><br><i><b>This email was generated by " + ResourceData.AppNameWithCode + "</b></i>";
            return Body;

        }

        public String ProblemCreate(Problem item, string requestedUserName, RequestType requestType)
        {
            String Body = "<br><b>Dear All,</b><br><br>";
            Body += "New Problem (Problem " + item.ProblemId.ToString() + ") has been created by " + requestedUserName + ".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Subject </b>: " + item.Subject;
            Body += "<br>";
            Body += "<b>Category </b>: " + requestType.Category.CategoryName;
            Body += "<br>";
            Body += "<b>Asset Type </b>: " + requestType.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Subcategory </b>: " + requestType.SubCategory.SubCategoryName;
            Body += "<br>";
            Body += "<b>Description </b>: " + item.Description;
            Body += "<br>";
            Body += "<b>Priority </b>: " + item.Priority.EnumDisplayName();
            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String ProblemClose(Problem item, string requestedUserName, RequestType requestType)
        {
            String Body = "<br><b>Dear All,</b><br><br>";
            Body += "<b>Problem " + item.ProblemId.ToString() + "</b> has been closed by " + requestedUserName + ".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Subject </b>: " + item.Subject;
            Body += "<br>";
            Body += "<b>Category </b>: " + requestType.Category.CategoryName;
            Body += "<br>";
            Body += "<b>Asset Type </b>: " + requestType.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Subcategory </b>: " + requestType.SubCategory.SubCategoryName;
            Body += "<br>";
            Body += "<b>Description </b>: " + item.Description;
            Body += "<br>";
            Body += "<b>Priority </b>: " + item.Priority.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Root Cause </b>: " + item.RootCause;
            Body += "<br>";
            Body += "<b>Impact </b>: " + item.Impact;
            Body += "<br>";
            Body += "<b>Symptoms </b>: " + item.Symptoms;
            Body += "<br>";
            Body += "<b>Solution </b>: " + item.Solution;

            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String ChangeCreate(Change item, string requestedUserName)
        {
            String Body = "<br><b>Dear All,</b><br><br>";
            Body += "New Change (Change " + item.ChangeId.ToString() + ") has been created by " + requestedUserName + ".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Subject </b>: " + item.Subject;
            Body += "<br>";
            Body += "<b>Asset </b>: " + item.AssetType.AssetCategory.EnumDisplayName() + " - " + item.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Request Type </b>: " + item.ChangeRequestType.ChangeRequestTypeName;
            Body += "<br>";
            Body += "<b>Description </b>: " + item.Description;
            Body += "<br>";
            Body += "<b>Change Type </b>: " + item.ChangeType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Priority </b>: " + item.Priority.EnumDisplayName();
            Body += "&nbsp;&nbsp;&nbsp;";
            Body += "<b>Risk </b>: " + item.Risk.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Planed Start Date </b>: " + item.StartDate.ToShortDateString();
            Body += "&nbsp;&nbsp;&nbsp;";
            Body += "<b>End Date </b>: " + item.EndDate.ToShortDateString();
            Body += "<br><br> Thank you.";
            return Body;

        }

        public String ChangePlan(Change item, string requestedUserName)
        {
            String Body = "<br><b>Dear Reviewer,</b><br><br>";
            Body += "Change Plan of Change " + item.ChangeId.ToString() + " has been updated by " + requestedUserName + ". <b>Please review</b>.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Subject </b>: " + item.Subject;
            Body += "<br>";
            Body += "<b>Asset </b>: " + item.AssetType.AssetCategory.EnumDisplayName() + " - " + item.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Request Type </b>: " + item.ChangeRequestType.ChangeRequestTypeName;
            Body += "<br>";
            Body += "<b>Description </b>: " + item.Description;
            Body += "<br>";
            Body += "<b>Change Type </b>: " + item.ChangeType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Priority </b>: " + item.Priority.EnumDisplayName();
            Body += "&nbsp;&nbsp;&nbsp;";
            Body += "<b>Risk </b>: " + item.Risk.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Planed Start Date </b>: " + item.StartDate.ToShortDateString();
            Body += "&nbsp;&nbsp;&nbsp;";
            Body += "<b>End Date </b>: " + item.EndDate.ToShortDateString();
            Body += "<br>";
            Body += "<b>Reason </b>: " + item.Reason;
            Body += "<br>";
            Body += "<b>Impact </b>: " + item.Impact;
            Body += "<br>";
            Body += "<b>Roll Out Plan </b>: " + item.RollOutPlan;
            Body += "<br>";
            Body += "<b>Back Out Plan </b>: " + item.BackOutPlan;
            Body += "<br><br> Thank you.";
            return Body;

        }

        public String ChangeReview(Change item, string requestedUserName, string url)
        {
            String Body = "<br><b>Dear Approvers,</b><br><br>";
            Body += "Change " + item.ChangeId.ToString() + " has been reviewed by " + requestedUserName + ". <b>Please  <a href='" + ResourceData.WebSiteURL.ToString() + url + "'>approve</a></b>.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Subject </b>: " + item.Subject;
            Body += "<br>";
            Body += "<b>Asset </b>: " + item.AssetType.AssetCategory.EnumDisplayName() + " - " + item.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Request Type </b>: " + item.ChangeRequestType.ChangeRequestTypeName;
            Body += "<br>";
            Body += "<b>Description </b>: " + item.Description;
            Body += "<br>";
            Body += "<b>Change Type </b>: " + item.ChangeType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Priority </b>: " + item.Priority.EnumDisplayName();
            Body += "&nbsp;&nbsp;&nbsp;";
            Body += "<b>Risk </b>: " + item.Risk.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Planed Start Date </b>: " + item.StartDate.ToShortDateString();
            Body += "&nbsp;&nbsp;&nbsp;";
            Body += "<b>End Date </b>: " + item.EndDate.ToShortDateString();
            Body += "<br>";
            Body += "<b>Reason </b>: " + item.Reason;
            Body += "<br>";
            Body += "<b>Impact </b>: " + item.Impact;
            Body += "<br>";
            Body += "<b>Roll Out Plan </b>: " + item.RollOutPlan;
            Body += "<br>";
            Body += "<b>Back Out Plan </b>: " + item.BackOutPlan;
            Body += "<br><br> Thank you.";
            return Body;

        }
        public String ChangeApproveReject(Change item, string requestedUserName, string status)
        {
            String Body = "<br><b>Dear All,</b><br><br>";
            Body += "<b>Change " + item.ChangeId.ToString() + "</b> has been <b>" + status + "</b> by " + requestedUserName + ".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Subject </b>: " + item.Subject;
            Body += "<br>";
            Body += "<b>Asset </b>: " + item.AssetType.AssetCategory.EnumDisplayName() + " - " + item.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Request Type </b>: " + item.ChangeRequestType.ChangeRequestTypeName;
            Body += "<br>";
            Body += "<b>Description </b>: " + item.Description;
            Body += "<br>";
            Body += "<b>Change Type </b>: " + item.ChangeType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Priority </b>: " + item.Priority.EnumDisplayName();
            Body += "&nbsp;&nbsp;&nbsp;";
            Body += "<b>Risk </b>: " + item.Risk.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Planed Start Date </b>: " + item.StartDate.ToShortDateString();
            Body += "&nbsp;&nbsp;&nbsp;";
            Body += "<b>End Date </b>: " + item.EndDate.ToShortDateString();
            Body += "<br>";

            Body += "<b>Reason </b>: " + item.Reason;
            Body += "<br>";
            Body += "<b>Impact </b>: " + item.Impact;
            Body += "<br>";
            Body += "<b>Roll Out Plan </b>: " + item.RollOutPlan;
            Body += "<br>";
            Body += "<b>Back Out Plan </b>: " + item.BackOutPlan;

            Body += "<br><br> Thank you. ";
            return Body;

        }

        public String ReleaseCreate(Release item, string requestedUserName)
        {
            String Body = "<br><b>Dear All,</b><br><br>";
            Body += "New Release (Release " + item.ReleaseId.ToString() + ") has been created by " + requestedUserName + ".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Subject </b>: " + item.Subject;
            Body += "<br>";
            Body += "<b>Asset </b>: " + item.AssetType.AssetCategory.EnumDisplayName() + " - " + item.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Request Type </b>: " + item.ChangeRequestType.ChangeRequestTypeName;
            Body += "<br>";
            Body += "<b>Description </b>: " + item.Description;
            Body += "<br>";
            Body += "<b>Release Type </b>: " + item.ReleaseType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Priority </b>: " + item.Priority.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Release Start Date </b>: " + item.StartDate.ToShortDateString();
            Body += "&nbsp;&nbsp;&nbsp;";
            Body += "<b>End Date </b>: " + item.EndDate.ToShortDateString();
            Body += "<br><br> Thank you.";
            return Body;

        }

        public String ReleasePlan(Release item, string requestedUserName)
        {
            String Body = "<br><b>Dear All,</b><br><br>";
            Body += "Release Plan of Release " + item.ReleaseId.ToString() + " has been updated by " + requestedUserName + ". Please proceed.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Subject </b>: " + item.Subject;
            Body += "<br>";
            Body += "<b>Asset </b>: " + item.AssetType.AssetCategory.EnumDisplayName() + " - " + item.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Request Type </b>: " + item.ChangeRequestType.ChangeRequestTypeName;
            Body += "<br>";
            Body += "<b>Description </b>: " + item.Description;
            Body += "<br>";
            Body += "<b>Release Type </b>: " + item.ReleaseType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Priority </b>: " + item.Priority.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Release Start Date </b>: " + item.StartDate.ToShortDateString();
            Body += "&nbsp;&nbsp;&nbsp;";
            Body += "<b>End Date </b>: " + item.EndDate.ToShortDateString();
            Body += "<br>";
            Body += "<b>Build Plan </b>: " + item.BuildPlan;
            Body += "<br>";
            Body += "<b>Test Plan </b>: " + item.TestPlan;
            Body += "<br><br> Thank you.";
            return Body;

        }

        public String ReleaseComplete(Release item, string requestedUserName)
        {
            String Body = "<br><b>Dear Reviewer,</b><br><br>";
            Body += "Release " + item.ReleaseId.ToString() + " has been completed by " + requestedUserName + ". <b>Please review</b>.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Subject </b>: " + item.Subject;
            Body += "<br>";
            Body += "<b>Asset </b>: " + item.AssetType.AssetCategory.EnumDisplayName() + " - " + item.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Request Type </b>: " + item.ChangeRequestType.ChangeRequestTypeName;
            Body += "<br>";
            Body += "<b>Description </b>: " + item.Description;
            Body += "<br>";
            Body += "<b>Release Type </b>: " + item.ReleaseType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Priority </b>: " + item.Priority.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Release Start Date </b>: " + item.StartDate.ToShortDateString();
            Body += "&nbsp;&nbsp;&nbsp;";
            Body += "<b>End Date </b>: " + item.EndDate.ToShortDateString();
            Body += "<br>";
            Body += "<b>Build Plan </b>: " + item.BuildPlan;
            Body += "<br>";
            Body += "<b>Test Plan </b>: " + item.TestPlan;
            Body += "<br><br> Thank you.";
            return Body;

        }

        public String ReleaseApproveReject(Release item, string requestedUserName, string status)
        {
            String Body = "<br><b>Dear All,</b><br><br>";
            Body += "<b>Release " + item.ReleaseId.ToString() + "</b> has been <b>" + status + "</b> by " + requestedUserName + ".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Subject </b>: " + item.Subject;
            Body += "<br>";
            Body += "<b>Asset </b>: " + item.AssetType.AssetCategory.EnumDisplayName() + " - " + item.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Request Type </b>: " + item.ChangeRequestType.ChangeRequestTypeName;
            Body += "<br>";
            Body += "<b>Description </b>: " + item.Description;
            Body += "<br>";
            Body += "<b>Release Type </b>: " + item.ReleaseType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Priority </b>: " + item.Priority.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Release Start Date </b>: " + item.StartDate.ToShortDateString();
            Body += "&nbsp;&nbsp;&nbsp;";
            Body += "<b>End Date </b>: " + item.EndDate.ToShortDateString();
            Body += "<br>";

            Body += "<b>Build Plan </b>: " + item.BuildPlan;
            Body += "<br>";
            Body += "<b>Test Plan </b>: " + item.TestPlan;

            Body += "<br><br> Thank you. ";
            return Body;

        }


        public String backupJobCompleted(BackupJob item, string requestedUserName)
        {
            String Body = "<br><b>Dear All,</b><br><br>";
            Body += "New Backup Job has been completed by " + requestedUserName + ".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Name </b>: " + item.BackupJobName;
            Body += "<br>";
            Body += "<b>Backup Date </b>: " + item.BackupDate.ToString("MM/dd/yyyy") + " | " + item.BackupDateName;
            Body += "<br>";
            Body += "<b>Type </b>: " + item.BackupType.EnumDisplayName();
            Body += "<br><br> Thank you.";
            return Body;

        }

        #region Scheduled Task

        public String TaskCreation(ScheduledTask item, string reviewByUser)
        {
            String Body = "<br><b>Dear " + item.User.FullName + ",</b><br><br>";
            Body += "A new task has been assigned to you by  " + reviewByUser + ".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Task Name </b>: " + item.TaskName;
            Body += "<br><b>Description </b>: " + item.Description;
            Body += "<br><b>Allocated Score</b>: " + item.Score;
            if (item.RepeatType == RepeatTypeEnum.Never)
            {
                Body += "<br><b>Due Date</b>: " + item.StartDate.ToShortDateString();
            }
            else if (item.RepeatType == RepeatTypeEnum.Week)
            {
                Body += "<br><b>Due Date/s</b>: Every Week - ";
                int days = 0;
                foreach (ScheduledDate d in item.ScheduledDates)
                {

                    if (days == 0)
                        Body += d.TaskDay;
                    else
                        Body += " / " + d.TaskDay;
                    days++;
                }
            }
            else if (item.RepeatType == RepeatTypeEnum.Month)
            {
                Body += "<br><b>Due Date/s</b>: Every Month - ";
                int days = 0;
                foreach (ScheduledDate d in item.ScheduledDates)
                {

                    if (days == 0)
                        Body += d.TaskDay;
                    else
                        Body += " / " + d.TaskDay;
                    days++;
                }
            }
            else if (item.RepeatType == RepeatTypeEnum.Year)
            {
                Body += "<br><b>Due Date/s</b>: ";
                int days = 0;
                foreach (ScheduledDate d in item.ScheduledDates)
                {

                    if (days == 0)
                        Body += d.TaskDate.ToShortDateString();
                    else
                        Body += " / " + d.TaskDate.ToShortDateString();
                    days++;
                }
            }
            Body += "<br>";
            Body += "<br>";

            Body += "Please log into the <a href='" + ResourceData.WebSiteURL.ToString() + "'>" + ResourceData.AppNameWithCode + " </a> to view more details.";
            Body += "<br><br> Thank you.";
            return Body;

        }

        public String TaskCompleted(ScheduledTask item, DateTime taskDate, string comment, string taskUser, string url)
        {
            String Body = "<br><b>Dear " + item.Reviewer.FullName + ",</b><br><br>";
            Body += item.TaskName + " ( " + taskDate.ToShortDateString() + " ) has been completed by " + taskUser + ".";
            Body += "<br>";
            Body += "<br><b>Task Owner Comment </b>: " + comment;
            Body += "<br><b>Allocated Score</b>: " + item.Score;
            if (item.RepeatType == RepeatTypeEnum.Never)
            {
                Body += "<br><b>Due Date</b>: " + item.StartDate.ToShortDateString();
            }
            else if (item.RepeatType == RepeatTypeEnum.Week)
            {
                Body += "<br><b>Due Date/s</b>: Every Week - ";
                int days = 0;
                foreach (ScheduledDate d in item.ScheduledDates)
                {

                    if (days == 0)
                        Body += d.TaskDay;
                    else
                        Body += " / " + d.TaskDay;
                    days++;
                }
            }
            else if (item.RepeatType == RepeatTypeEnum.Month)
            {
                Body += "<br><b>Due Date/s</b>: Every Month - ";
                int days = 0;
                foreach (ScheduledDate d in item.ScheduledDates)
                {

                    if (days == 0)
                        Body += d.TaskDay;
                    else
                        Body += " / " + d.TaskDay;
                    days++;
                }
            }
            else if (item.RepeatType == RepeatTypeEnum.Year)
            {
                Body += "<br><b>Due Date/s</b>: ";
                int days = 0;
                foreach (ScheduledDate d in item.ScheduledDates)
                {

                    if (days == 0)
                        Body += d.TaskDate.ToShortDateString();
                    else
                        Body += " / " + d.TaskDate.ToShortDateString();
                    days++;
                }
            }
            Body += "<br>";
            Body += "<br>";

            Body += "Please log into the <a href='" + ResourceData.WebSiteURL.ToString() + "'>" + ResourceData.AppNameWithCode + " </a> to view more details ";
            Body += "and to proceed with the <a href='" + ResourceData.WebSiteURL.ToString() + url + "'>review </a> process.";
            Body += "<br><br> Thank you.";
            return Body;

        }

        public String TaskReviewed(ScheduledTask item, DateTime taskDate, string comment, string taskUser, string status)
        {
            String Body = "<br><b>Dear " + item.User.FullName + ",</b><br><br>";
            Body += item.TaskName + " ( " + taskDate.ToShortDateString() + " ) has been " + status + " by " + taskUser + ".";
            Body += "<br>";
            Body += "<br><b>Reviewer Comment </b>: " + comment;

            Body += "<br>";
            Body += "<br>";

            Body += "Please log into the <a href='" + ResourceData.WebSiteURL.ToString() + "'>" + ResourceData.AppNameWithCode + " </a> to view more details.";
            Body += "<br><br> Thank you.";
            return Body;

        }

        #endregion

        public String ChecklistEmail(long? teamId, DateTime taskDate, string teamName)
        {

            bool isValid = false;

            String srtEmail = "";
            TaskCategoryService _taskCatService = new TaskCategoryService();
            TaskUpdateService _taskUpdateService = new TaskUpdateService();

            srtEmail += "<div style='width:100%; background-color:#fff; padding:10px;'> ";
            srtEmail += " <span style='font-family:arial, verdana, sans; font-weight:700;'> " + teamName + " | Daily Check List - " + taskDate.ToShortDateString() + "  </span>";
            srtEmail += " </div>";

            srtEmail += " ";
            srtEmail += " <table width='100%' style='border: 2px solid #646161; border-spacing: 0; border-collapse: collapse;font-family:arial, verdana, sans; font-weight:400;'>";

            var cats = _taskCatService.GetItemsByCheckList(teamId, taskDate, "").Select(t => t.TaskCategoryId).Distinct();
            foreach (long catId in cats)
            {
                //item.TaskCategoryId = catId;
                var _cat = _taskCatService.GetItemAsNoTracking(catId, "");

                srtEmail += " <tr style='background:#1F7AD6;'>";

                srtEmail += " <td style='background:#1F7AD6;padding:8px; border: 1px solid #ddd;color:#2C2D2D;font-weight:600; ' width='70%'>" + _cat.TaskCategoryName + "</td> ";
                srtEmail += " <td style='background:#1F7AD6;padding:8px; border: 1px solid #ddd;color:#2C2D2D;font-weight:600; ' width='30%' align='right'>Weightage : " + _cat.Weightage + " %</td> ";
                srtEmail += " </tr>";

                var tasks = _taskUpdateService.GetItemsByUser("", catId, taskDate, taskDate, true, "ScheduledTask,ScheduledTask.User").ToList().OrderByDescending(o => o.IsFollowupNeeded);
                foreach (TaskUpdate _task in tasks)
                {
                    srtEmail += " <tr style='background:#D5DBDB ;'>";
                    //srtEmail += " <td style='background:#D5DBDB ;padding:8px; border: 1px solid #ddd; ' colspan='2'>" + _task.ScheduledTask.TaskName + "</td> ";
                    //srtEmail += " <td style='background:#D5DBDB ;padding:8px; border: 1px solid #ddd; ' align='right'>" + _task.ScheduledTask.User.FullName + "</td> ";

                    if (_task.IsFollowupNeeded)
                        srtEmail += " <td style='background:#F38585 ;padding:8px; border: 1px solid #ddd; ' colspan='2'><span style='color:#1D1D1D;font-weight:400;margin-bottom:5px'>" + _task.ScheduledTask.TaskName + " &nbsp;&nbsp;(&nbsp; " + _task.ScheduledTask.User.FullName + "&nbsp;)</span><br>Comment :" + _task.Comment + "</td> ";
                    else
                        srtEmail += " <td style='background:#4FD16C ;padding:8px; border: 1px solid #ddd; ' colspan='2'><span style='color:#1D1D1D;font-weight:400;padding-bottom:5px; '>" + _task.ScheduledTask.TaskName + "  &nbsp;&nbsp;(&nbsp; " + _task.ScheduledTask.User.FullName + " &nbsp;)</span><br>Comment :" + _task.Comment + "</td> ";

                    srtEmail += " </tr>";
                    //if (_task.Status == ScheduledTaskStatusEnum.Pending)
                    //    return "";

                    //srtEmail += " <tr style='background:#FCFBFA;'>";

                    //if (_task.IsFollowupNeeded)
                    //    srtEmail += " <td style='background:#F5B7B1;padding:8px; border: 1px solid #ddd; ' colspan='2'>Comment :" + _task.Comment + "</td> ";
                    //else
                    //    srtEmail += " <td style='background:#FCFBFA;padding:8px; border: 1px solid #ddd; ' colspan='2'>Comment :" + _task.Comment + "</td> ";
                    //srtEmail += " </tr>";
                }

            }

            srtEmail += " </table>";

            srtEmail += "<br>";
            srtEmail += "<br>";

            srtEmail += "Please log into the <a href='" + ResourceData.WebSiteURL.ToString() + "'>" + ResourceData.AppNameWithCode + " </a> to view more details.";
            srtEmail += "<br><br> Thank you.";
            return srtEmail;

        }


        #region Event

        public String EventOpen(Event item, string requestedUserName)
        {
            String Body = "<br><b>Dear All,</b><br><br>";
            Body += "New Event (Event " + item.EventId.ToString() + ") has been created by " + requestedUserName + ".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Event Type </b>: " + item.EventType.EventTypeName;
            Body += "<br>";
            Body += "<b>Subject </b>: " + item.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + item.Description;
            Body += "<br>";
            Body += "<b>Event Date/Time </b>: " + item.EventDate.ToString();
            Body += "<br><br> Thank you.";
            return Body;

        }

        public String EventClosed(Event item, string requestedUserName)
        {
            String Body = "<br><b>Dear All,</b><br><br>";
            Body += "Event (Event " + item.EventId.ToString() + ") has been closed by " + requestedUserName + ".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Event Type </b>: " + item.EventType.EventTypeName;
            Body += "<br>";
            Body += "<b>Subject </b>: " + item.Subject;
            Body += "<br>";
            Body += "<b>Action Taken </b>: " + item.ActionTaken;
            Body += "<br>";
            Body += "<b>Date/Time </b>: " + item.UpdatedDate.ToString();
            Body += "<br><br> Thank you.";
            return Body;

        }

        #endregion

        #region Access Request

        public String AccessRequestCreate(AccessRequest request)
        {
            String Body = "<br><b>Dear " + request.ApprovalByUser.FullName + ",</b><br><br>";
            Body += "New " + request.AccessRequestType.Name + " request has been raised by <b>" + request.CreatedUser.FullName + "</b> with the below details & pending your approval.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.AccessRequestId;
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Justification </b>: " + request.Justification;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Access Type  </b>: " + request.AccessType.EnumDisplayName();
            Body += "<br>";
            if (request.AccessType == AllocatedTypeEnum.Internal)
                Body += "<b>Requested For  </b>: " + request.RequestedUser.FullName;
            else
                Body += "<b>Requested For  </b>: " + request.Organization;

            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String AccessRequestPending(AccessRequest request)
        {
            String Body = "<br><b>Dear " + request.WorkflowLevelType.EnumDisplayName() + ",</b><br><br>";
            Body += "Please be informed that a new " + request.AccessRequestType.Name + " request is pending from your end. Kindly take necessary action to accommodate the request.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.AccessRequestId;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Justification </b>: " + request.Justification;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Access Type  </b>: " + request.AccessType.EnumDisplayName();
            Body += "<br>";
            if (request.AccessType == AllocatedTypeEnum.Internal)
                Body += "<b>Requested For  </b>: " + request.RequestedUser.FullName;
            else
                Body += "<b>Requested For  </b>: " + request.Organization;

            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String AccessRequestCancel(AccessRequest request, string comment)
        {
            String Body = "<br><b>Dear " + request.ApprovalByUser.FullName + ",</b><br><br>";
            Body += "The above " + request.AccessRequestType.Name + " Request has been cancelled by " + request.CreatedUser.FullName + ". Please refer comments to get more details.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.AccessRequestId;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Justification </b>: " + request.Justification;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Access Type  </b>: " + request.AccessType.EnumDisplayName();
            Body += "<br>";
            if (request.AccessType == AllocatedTypeEnum.Internal)
                Body += "<b>Requested For  </b>: " + request.RequestedUser.FullName;
            else
                Body += "<b>Requested For  </b>: " + request.Organization;
            Body += "<br>";
            Body += "<b>Comment </b>: " + comment;
            Body += "<br><br> Thank you! ";
            return Body;

        }
        public String AccessRequestReject(AccessRequest request, string comment)
        {
            String Body = "<br><b>Dear " + request.CreatedUser.FullName + ",</b><br><br>";
            Body += "The above " + request.AccessRequestType.Name + " Request has been rejected by " + request.ApprovalByUser.FullName + ". Please refer comments to get more details.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.AccessRequestId;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Justification </b>: " + request.Justification;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Access Type  </b>: " + request.AccessType.EnumDisplayName();
            Body += "<br>";
            if (request.AccessType == AllocatedTypeEnum.Internal)
                Body += "<b>Requested For  </b>: " + request.RequestedUser.FullName;
            else
                Body += "<b>Requested For  </b>: " + request.Organization;
            Body += "<br>";
            Body += "<b>Comment </b>: " + comment;
            Body += "<br><br> Thank you! ";
            return Body;

        }
        public String AccessRequestRejectWorkflow(AccessRequest request, string comment)
        {
            String Body = "<br><b>Dear " + request.CreatedUser.FullName + ",</b><br><br>";
            Body += "The above " + request.AccessRequestType.Name + " Request has been rejected by " + request.WorkflowLevelType.EnumDisplayName() + " of " + request.Team.TeamName + " Team. Please refer comments to get more details.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.AccessRequestId;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Justification </b>: " + request.Justification;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Access Type  </b>: " + request.AccessType.EnumDisplayName();
            Body += "<br>";
            if (request.AccessType == AllocatedTypeEnum.Internal)
                Body += "<b>Requested For  </b>: " + request.RequestedUser.FullName;
            else
                Body += "<b>Requested For  </b>: " + request.Organization;
            Body += "<br>";
            Body += "<b>Comment </b>: " + comment;
            Body += "<br><br> Thank you! ";
            return Body;

        }
        public String AccessRequestComplete(string implemetedByName, AccessRequest request,string comment)
        {
            String Body = "";
            if (request.AccessType == AllocatedTypeEnum.Internal)
                Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";
            else
                Body = "<br><b>Dear " + request.CreatedUser.FullName + ",</b><br><br>";

            Body += "We are pleased to inform you that your " + request.AccessRequestType.Name + " request has been successfully completed. This email serves as a confirmation that the requested service has been accommodated.";

            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.AccessRequestId;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Duration Type </b>: " + request.DurationType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Access Type </b>: " + request.AccessType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Implemeted By </b>: " + implemetedByName;
            Body += "<br>";
            Body += "<b>Comment </b>: " + comment;

            if (request.AccessRequestType.CompletionEmailInstructions != null || request.AccessRequestType.CompletionEmailInstructions != "")
                Body += "<br><br> " + request.AccessRequestType.CompletionEmailInstructions;

            Body += "<br><br> Thank You. ";
            Body += "<br> <b>" + request.Team.TeamName + "</b>";
            Body += "<br> National Development Bank PLC  ";

            return Body;

        }

        #endregion


        #region Change Request
        public String ChangeRequestCreate(ChangeRequest request)
        {
            String Body = "<br><b>Dear " + request.ApprovalByUser.FullName + ",</b><br><br>";
            Body += "New Change Request has been raised by <b>" + request.RequestedUser.FullName + "</b> with the below details & pending your approval.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Justification </b>: " + request.Justification;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();

            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String ChangeRequestCancel(ChangeRequest request, string comment)
        {
            String Body = "<br><b>Dear " + request.ApprovalByUser.FullName + ",</b><br><br>";
            Body += "The below Change Request has been cancelled by " + request.RequestedUser.FullName + ". Please refer comments to get more details.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Justification </b>: " + request.Justification;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Comment </b>: " + comment;
            Body += "<br><br> Thank you! ";
            return Body;

        }
        

        public String ChangeRequestApprove(ChangeRequest request)
        {
            String Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";
            Body += "Your change request has been approved by "+request.ApprovalByUser.FullName+" and sent to the <b>"+request.Team.TeamName+"</b> team to proceed.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Request Category # </b>: " + request.ChangeRequestCategory.Name;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();


            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String ChangeRequestReject(ChangeRequest request,string comment)
        {
            String Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";
            Body += "Your change request has been <b>rejected</b> by " + request.ApprovalByUser.FullName + " with the following comment:";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Request Category # </b>: " + request.ChangeRequestCategory.Name;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Comment  </b>: " + comment;


            Body += "<br><br> Thank you! ";
            return Body;

        }
        public String ChangeRequestPending(ChangeRequest request)
        {
            String Body = "<br><b>Dear " + request.Team.TeamName + " Team,</b><br><br>";
            Body += "Please be informed that a new Change Request is pending from your end. Kindly take necessary action to accommodate the request.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Request Category # </b>: " + request.ChangeRequestCategory.Name;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Justification </b>: " + request.Justification;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Requested By  </b>: " + request.RequestedUser.FullName;


            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String ChangeRequestChangeReject(ChangeRequest request, string comment)
        {
            String Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";
            Body += "Your change request has been <b>rejected</b> by " + request.ImplementedByUser.FullName + " with the following comment:";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Request Category # </b>: " + request.ChangeRequestCategory.Name;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Comment  </b>: " + comment;


            Body += "<br><br> Thank you! ";
            return Body;

        }
        public String ChangeRequestChangeApprove(ChangeRequest request)
        {
            String Body = "<br><b>Dear " + request.Team.TeamName + " Team Head,</b><br><br>";
            Body += "Please be informed that a new Change Request approval is pending from your end. Kindly take necessary action to accommodate the request.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Request Category # </b>: " + request.ChangeRequestCategory.Name;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Justification </b>: " + request.Justification;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Requested By  </b>: " + request.RequestedUser.FullName;
            //Body += "<br>";
            //Body += "<b>Change Area </b>: " + impData.ChangeArea.Name;
            //Body += "<br>";
            //Body += "<b>Planned Change  </b>: " + impData.PlannedChange;
            //Body += "<br>";
            //Body += "<b>Risk Assessment  </b>: " + impData.RiskAssessment;

            Body += "<br><br> Thank you! ";
            return Body;

        }


        public String CRChangeApproved(ChangeRequest request)
        {
            String Body = "<br><b>Dear " + request.Team.TeamName + " Team,</b><br><br>";
            Body += "Please be informed that request "+request.ChangeRequestId+" Change has been approved. Please take the necessary action to implement the request.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Request Category # </b>: " + request.ChangeRequestCategory.Name;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Requested By  </b>: " + request.RequestedUser.FullName;
            //Body += "<br>";
            //Body += "<b>Change Area </b>: " + impData.ChangeArea.Name;
            //Body += "<br>";
            //Body += "<b>Planned Change  </b>: " + impData.PlannedChange;
            //Body += "<br>";
            //Body += "<b>Risk Assessment  </b>: " + impData.RiskAssessment;

            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String CRChangeRejected(ChangeRequest request, string comment)
        {
            String Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";
            Body += "Your change request has been <b>rejected</b> by Change Authorizer with the following comment:";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Request Category # </b>: " + request.ChangeRequestCategory.Name;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Comment  </b>: " + comment;


            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String CRChangeSentHigherApproval(ChangeRequest request)
        {
            String Body = "<br><b>Dear Authorizer,</b><br><br>";
            Body += "Please be informed that a new Change Request is pending from your end. Kindly review the details and take the necessary action at your earliest convenience.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Request Category # </b>: " + request.ChangeRequestCategory.Name;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Requested By  </b>: " + request.RequestedUser.FullName;
            //Body += "<br>";
            //Body += "<b>Change Area </b>: " + impData.ChangeArea.Name;
            //Body += "<br>";
            //Body += "<b>Planned Change  </b>: " + impData.PlannedChange;
            //Body += "<br>";
            //Body += "<b>Risk Assessment  </b>: " + impData.RiskAssessment;

            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String CRChangeRejectedByImplementer(ChangeRequest request, string comment)
        {
            String Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";
            Body += "Your change request has been <b>rejected</b> by Change Implementer with the following comment:";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Request Category # </b>: " + request.ChangeRequestCategory.Name;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Comment  </b>: " + comment;


            Body += "<br><br> Thank you! ";
            return Body;

        }
        public String CRChangeRejectedByReviewer(ChangeRequest request, string comment)
        {
            String Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";
            Body += "Your change request has been <b>rejected</b> by Change Reviewer with the following comment:";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Request Category # </b>: " + request.ChangeRequestCategory.Name;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Comment  </b>: " + comment;


            Body += "<br><br> Thank you! ";
            return Body;

        }


        public String Downtime(ChangeImplementData request)
        {
            String Body = "<br><b>Dear All,</b><br><br>";
            Body += "Please be informed that, there will be a planned system outage as per the below schedule.";
            Body += "<br>";
            Body += "<br>";
            Body += "<table style=\"width: 100 %; \" border=\"1\" cellpadding=\"2\">";
            Body += "<tbody>";
            Body += "<tr><td><b>Date </b> </td><td>"+ Convert.ToDateTime(request.DowntimePlannedDate).ToString("dd-MMM-yyyy") + "</td></tr>";
            Body += "<tr><td><b>Time Period </b> </td><td>" + request.DowntimeTimePeriod + "</td></tr>";
            Body += "<tr><td><b>Downtime Duration </b> </td><td>" + request.Downtime + "</td></tr>";
            Body += "<tr><td><b>Impacted Area/s  </b> </td><td>" + request.DowntimeImpactedAreas + "</td></tr>";
            Body += "<tr><td><b>Purpose </b> </td><td>"+request.DowntimeTimePurpose+"</td></tr>";
            Body += "</tbody>";
            Body += "</table>";
            //Body += "<b>Date </b>: " + Convert.ToDateTime(request.DowntimePlannedDate).ToString("dd-MMM-yyyy");
            //Body += "<br>";
            //Body += "<b>Time Period </b>: " + request.DowntimeTimePeriod;
            //Body += "<br>";
            //Body += "<b>Downtime Duration </b>: " +request.Downtime;
            //Body += "<br>";
            //Body += "<b>Impacted Area/s </b>: " + request.DowntimeImpactedAreas;
            //Body += "<br>";
            //Body += "<b>Purpose </b>: Implementation of CR (" + request.ChangeRequestId + ")";
            //Body += "<br>";
            Body += "<br><br> Thank you! ";
            return Body;

        }


        public String CRChangeClosed(ChangeRequest request)
        {
            String Body = "<br><b>Dear " + request.RequestedUser.FullName + " Team,</b><br><br>";
            Body += "Please be informed that request " + request.ChangeRequestId + " Change has been Completed.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.ChangeRequestId;
            Body += "<br>";
            Body += "<b>Request Category # </b>: " + request.ChangeRequestCategory.Name;
            Body += "<br>";
            Body += "<b>Requested Date </b>: " + request.RequestedDate.ToString();
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Duration Type  </b>: " + request.DurationType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Requested By  </b>: " + request.RequestedUser.FullName;

            Body += "<br><br> Thank you! ";
            return Body;



        }
        #endregion

        #region Incident

        public String NewIncident(IncidentRequest request)
        {
            String Body = "<br><b>Dear " + request.Level01Team.TeamName + " Team,</b><br><br>";
            Body += "A new Incident has been logged into the system that requires your attention:";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.IncidentRequestId;
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Business Impact </b>: " + request.BusinessImpact;
            Body += "<br>";
            Body += "<b>Impact </b>: " + request.Impact.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Occurred Date/Time </b>: " + request.OccurredDate.ToString();
            
            Body += "<br><br> Please review the incident details at your earliest convenience and take the necessary actions to address it promptly.";
            Body += "<br><br> Thank you! ";
            return Body;

        }
        public String IncidentEscalation(IncidentRequest request)
        {
            String Body = "<br><b>Dear " + request.PendingTeam.TeamName + " Team,</b><br><br>";
            Body += "A new Incident has been escalated to your team and requires your attention:";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.IncidentRequestId;
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Business Impact </b>: " + request.BusinessImpact;
            Body += "<br>";
            Body += "<b>Impact </b>: " + request.Impact.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Occurred Date/Time </b>: " + request.OccurredDate.ToString();

            Body += "<br><br> Please review the incident details at your earliest convenience and take the necessary actions to address it promptly.";
            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String IncidentCompleted(IncidentRequest request)
        {
            String Body = "<br><b>Dear " + request.PendingTeam.TeamName + " Team Head,</b><br><br>";
            Body += "Please be informed that a new Incident Request review is pending from your end. Kindly take necessary action to accommodate the request.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.IncidentRequestId;
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Business Impact </b>: " + request.BusinessImpact;
            Body += "<br>";
            Body += "<b>Impact </b>: " + request.Impact.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Occurred Date/Time </b>: " + request.OccurredDate.ToString();

            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String IncidentReviewed(IncidentRequest request)
        {
            String Body = "<br><b>Dear Incident Manager,</b><br><br>";
            Body += "Please be informed that a new Incident Request is awaiting closure. Kindly take the necessary action to review and close the request.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.IncidentRequestId;
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Business Impact </b>: " + request.BusinessImpact;
            Body += "<br>";
            Body += "<b>Impact </b>: " + request.Impact.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Occurred Date/Time </b>: " + request.OccurredDate.ToString();

            Body += "<br><br> Thank you! ";
            return Body;

        }

        public String IncidentClosed(IncidentRequest request)
        {
            String Body = "<br><b>Dear "+ request.RequestedUser.FullName + ",</b><br><br>";
            Body += "Please be informed that the incident you logged has been closed.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.IncidentRequestId;
            Body += "<br>";
            Body += "<b>Subject </b>: " + request.Subject;
            Body += "<br>";
            Body += "<b>Description </b>: " + request.Description;
            Body += "<br>";
            Body += "<b>Business Impact </b>: " + request.BusinessImpact;
            Body += "<br>";
            Body += "<b>Impact </b>: " + request.Impact.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Occurred Date/Time </b>: " + request.OccurredDate.ToString();

            Body += "<br><br> Thank you! ";
            return Body;

        }

        #endregion



        #region Remote access request

        // remote access ticket initiation
        public String RemoteAcessInitiated(RemoteAccessRequest request)
        {
            String Body;
            if(request.ApprovedAVPOrVP != null)
            {
                 Body = "<br><b>Dear " + request.ApprovedAVPOrVPUser.FullName + ",</b><br><br>";

            }
            else
            {
                 Body = "<br><b>Dear " + request.ApprovedSupervisorUser.FullName + ",</b><br><br>";
            }
            Body += "A new Remote Work Request has been submitted by " +request.RequestedUser.FullName+ " ("+request.RequestedUser.EmpNo+")"+ ".Please review and take appropriate action. ";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.RemoteAccessRequestId;
            Body += "<br>";
            Body += "<b>Requester Name </b>: " + request.RequestedUser.FullName;
            Body += "<br>";
            Body += "<b>Employee ID: </b>: " + request.RequestedUser.EmpNo;
            Body += "<br>";
            Body += "<b>Department </b>: " + request.RequestedUser.DepartmentName;
            Body += "<br>";
            Body += "<b>Job Title </b>: " + request.RequestedUser.DesignationName;
            Body += "<br>";
            Body += "<b>Requested Access </b>: " + request.RemoteAccessType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Justification </b>: " + request.BusinessJustification;
            Body += "<br>";
            Body += "<b>Proposed Duration </b>: " + request.StartDate.ToShortDateString() + " to " + request.EndDate.ToShortDateString();
            Body += "<br>";
            Body += "<br>";
            Body += "Kindly log in to the ITSM system and review under <b>Pending Approvals → Remote Work Requests</b>. ";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }

        // supervisor approval/reject of remote access
        public String RemoteSupervisorApprovalRejection(RemoteAccessRequest request,String Comment,DateTime DecisionDate,bool isReject)
        {
            var statement = isReject == true ? "rejected" : "approved";
            string recipientName = "";
            if (request.ApprovedAVPOrVPUser != null)
            {
                recipientName = request.ApprovedAVPOrVPUser.FullName;
            }
            else
            {
                recipientName = request.RequestedUser.FullName;
            }
            String Body = "<br><b>Dear " + recipientName + ",</b><br><br>";
           
            Body += "The immediate supervisor, " +request.ApprovedSupervisorUser.FullName+ ",has "+statement+" the remote work request from " +request.RequestedUser.FullName+ ".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.RemoteAccessRequestId;
            Body += "<br>";
            Body += "<b>Requester Name </b>: " + request.RequestedUser.FullName;     
            Body += "<br>";
            Body += "<b>Justification </b>: " + request.BusinessJustification;
            Body += "<br>";
            Body += "<b>Supervisor Comments </b>: " + Comment;
            Body += "<br>";
            Body += "<b>Decision Date </b>: " + DecisionDate;
            Body += "<br>";
            Body += "<br>";
            Body += "Please review and proceed with the next approval action in ITSM.";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }


        // avp/vp tolerance exceeded email
        public String RemoteavpvpToleranceExceeded(RemoteAccessRequest request)
        {
            String Body = "<br><b>Dear Risk Team,</b><br><br>";

            Body += "The Line AVP/VP, " + request.ApprovedAVPOrVPUser.FullName + ",has approved a remote work request from that exceeds the risk-tolerable number of staffs.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Justification for Exceeding Tolerance:</b><br>";
            Body += request.ToleranceLimitExceededJustification;
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.RemoteAccessRequestId;
            Body += "<br>";
            Body += "<b>Requester Name </b>: " + request.RequestedUser.FullName;
            Body += "<br>";
            Body += "<b>Department / Role </b>: " + request.Department.DepartmentName;
            Body += "<br>";
            Body += "<b>Requested Access: </b>: " + request.RemoteAccessType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Requested Duration </b>: " + request.StartDate.ToShortDateString() + " to " + request.EndDate.ToShortDateString();
            Body += "<br>";
            Body += "<br>";
            Body += "Please review the justification and proceed with the risk assessment.";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }



        // avp/vp approval/reject of remote access

        public String RemoteavpvpApprovalRejection(RemoteAccessRequest request,String Comment, DateTime DecisionDate, bool isReject)
        {
            var statement = isReject == true ? "rejected" : "approved";
            String Body = "<br><b>Dear HR Work Administrator,</b><br><br>";

            Body += "The Line AVP/VP, " + request.ApprovedAVPOrVPUser.FullName + ",has "+statement+ " the remote work request submitted by " +request.RequestedUser.FullName;
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.RemoteAccessRequestId;
            Body += "<br>";
            Body += "<b>Requester Name </b>: " + request.RequestedUser.FullName;
            Body += "<br>";
            Body += "<b>Access Requested </b>: " + request.RemoteAccessType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>AVP/VP Comments </b>: " + Comment;
            Body += "<br>";
            Body += "<b>Decision Date </b>: " + DecisionDate;
            Body += "<br>";
            Body += "<br>";
            Body += "Please proceed with the next action accordingly.";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }


        // risk team approve/reject 
        public String RemoteRiskTeamApprovalRejection(RemoteAccessRequest request, String Comment, bool isReject)
        {
            var statement = isReject == true ? "rejected" : "approved";
            String Body = "<br><b>Dear HR Work Administrator,</b><br><br>";  // or name of the hr person

            Body += "The Risk Department has completed the review of justification for the remote work request by "+request.RequestedUser.FullName;
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.RemoteAccessRequestId;
            Body += "<br>";
            Body += "<b>Decision </b>: " + statement;
            Body += "<br>";
            Body += "<b>Risk Comments </b>: " + Comment;
            Body += "<br>";
            Body += "<b>Reviewed By </b>: " + request.FinalApprovalByUser.FullName;          
            Body += "<br>";
            Body += "<br>";
            Body += "Please proceed with the next action accordingly.";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }

        // request for clarification email
        public String RemoteRequestForClarification(RemoteAccessRequest request, String ReasonForClarification)
        {
            String Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";

            Body += "Your remote work request requires additional information for HR verification.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.RemoteAccessRequestId;      
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Reason For Clarification Request </b>:<br> " + ReasonForClarification;
            Body += "<br>";
            Body += "<br>";
            Body += "Please update your request in ITSM and resubmit for review.";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }

        // clarification provided email from requester
        public String RemoteClarificationProvided(RemoteAccessRequest request)
        {
            String Body = "<br><b>Dear HR Work Admin,</b><br><br>";

            Body += "The requester, "+request.RequestedUser.FullName+" , has submitted the required clarifications for your review.";
            Body += "<br>";
            Body += "<br>";     
            Body += "Please recheck and proceed with the approval process.";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }

        // HR recommedation email
        public String RemoteHRRecommendation(RemoteAccessRequest request, String Comment)
        {
            String Body = "<br><b>Dear IT Security Head,</b><br><br>"; // or name of the it sec head guy

            Body += "The HR Work Administrator has reviewed the remote work request and provided recommendations for approval.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.RemoteAccessRequestId;
            Body += "<br>";
            Body += "<b>Requester</b>: " + request.RequestedUser.FullName;
            Body += "<br>";
            Body += "<b>Duration </b>: " + request.StartDate.ToShortDateString() + " - " + request.EndDate.ToShortDateString();
            Body += "<br>";
            Body += "<b>Recommended Access Type </b>: " + request.RemoteAccessType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>HR Comments </b>:<br> " + Comment;
            Body += "<br>";
            Body += "<br>";
            Body += "Please update your request in ITSM and resubmit for review.";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }

        // IT sec head approval / rejection
        public String RemoteITSecHeadApprovalRejection(RemoteAccessRequest request, String Comment, DateTime ApprovalDate, bool isReject)
        {
            var statement = isReject == true ? "rejected" : "approved";
            String Body = "<br><b>Dear IT SVP,</b><br><br>";

            Body += "The Head of IT Security has "+statement+" the remote work request by "+request.RequestedUser.FullName+".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.RemoteAccessRequestId;
            Body += "<br>";
            Body += "<b>Access Type </b>: " + request.RemoteAccessType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Security Comments </b>: " + Comment;
            Body += "<br>";
            Body += "<b>Approval Date </b> : " + ApprovalDate.ToShortDateString();

            Body += "<br>";
            Body += "<br>";
            Body += "Please review and proceed with the next approval action in ITSM.";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }

        // implementer network approve
        public String RemoteImplementerNetwork(RemoteAccessRequest request, String Comment)
        {
            var IsAddedToGroup = request.IsAddedToGroup == true ? "Yes" : "No";
            var IsWifiAccessAllow = request.IsWifiAccessAllow == true ? "Yes" : "No";
            
            String Body = request.RemoteAccessType == RemoteAccessTypeEnum.Citrix ? "<br><b>Dear Helpdesk Team,</b><br><br>" :
                "<br><b>Dear Security Implementer,</b><br><br>";

            Body += "Network implementation for "+request.RequestedUser.FullName+" has been completed.<br>Please proceed with endpoint verification and certification. ";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.RemoteAccessRequestId;
            Body += "<br>";
            Body += "<b>User Added to Group </b> :" + IsAddedToGroup;
            Body += "<br>";
            Body += "<b>Wi-Fi Access Enabled </b> :" + IsWifiAccessAllow;
            Body += "<br>";
            Body += "<b>Comments </b>: " + Comment;              

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }

        // implementer security approve
        public String RemoteImplementerSecurity(RemoteAccessRequest request)
        {
            var IsCertificateProvided = request.IsCertificateProvided == true ? "Yes" : "No";
            String Body = "<br><b>Dear Helpdesk Team,</b><br><br>";

            Body += "The endpoint verification and certification for "+request.RequestedUser.FullName+" have been completed.<br>Please coordinate with the user to ensure successful access setup.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.RemoteAccessRequestId;
            Body += "<br>";
            Body += "<b>Certificate Issued </b>: " + IsCertificateProvided;
            Body += "<br>";
            Body += "<b>Implemented By </b>: " + request.FinalApprovalByUser.FullName;


            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }


        // helpdesk complete
        public String RemoteHelpDeskCompletion(RemoteAccessRequest request)
        {
           
            String Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";

            Body += "Your remote work setup has been successfully completed and verified.<br>The ticket "+request.RemoteAccessRequestId+" has now been closed. ";
            Body += "<br>";          
            Body += "<br>";
            Body += "<b>Access Type </b>: " + request.RemoteAccessType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Activation Date </b>: " + request.StartDate.ToShortDateString();
            Body += "<br>";
            Body += "<b>Support Contact: </b>: it.helpdesk@12345.com";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }

        // revokation reminder 2 weeks before expiry date
        public String RemoteRevokationTwoWeeksBefore(RemoteAccessRequest request)
        {   

            String Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";

            Body += "Your remote work access will be expired within <b>two weeks</b>.<br>If continued access is required please reapply.";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }



        // final reminder on expiry date
        public String RemoteRevokationFinal(RemoteAccessRequest request)
        {

            String Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";

            Body += "Your remote work access is scheduled for revocation due to expiry.<br>If continued access is required, please reapply";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.RemoteAccessRequestId;
            Body += "<br>";
            Body += "<b>Access Type </b>: " + request.RemoteAccessType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Expiry Date </b>: " + request.EndDate.ToShortDateString();


            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }

        // inactive email

        public String RemoteAccessInactiveEmail(RemoteAccessRequest request)
        {

            String Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";

            Body += "The system has identified that "+ request.RequestedUser.FullName + "’s remote access has been inactive for over 30 days. ";
            Body += "<br>";
            Body += "<br>";
            Body += "Please confirm continuation as per policy.If no response is given within two weeks access will be automatically disabled.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Request # </b>: " + request.RemoteAccessRequestId;
            Body += "<br>";
            Body += "<b>Access Type </b>: " + request.RemoteAccessType.EnumDisplayName();
            Body += "<br>";
            Body += "<b>Expiry Date </b>: " + request.EndDate.ToShortDateString();


            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }


        public String RaiseClarificationEmail(RemoteAccessRequest request, string reason)
        {

            String Body = "<br><b>Dear " + request.RequestedUser.FullName + ",</b><br><br>";

            Body += "Your remote work request requires additional information for approval.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Clarification Requested </b>: " + reason;
            Body += "<br><br>";
            Body += "Please update your request in ITSM - Remote work and resubmit for review. ";
            Body += "<br>";



            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }


         public String ReplyClarificationEmail(RemoteAccessRequest request,RemoteAccessRequestUpdate latestRequest, string reply,string requestedBy, string assignedTo)
        {

            String Body = "<br><b>Dear " + requestedBy + ",</b><br><br>";

            Body += assignedTo + " has submitted the required clarifications for your review.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Clarification Requested: </b>: " + latestRequest.Comment + "<br><br>";
            Body += "<b>Clarification Provided: </b>: " + reply;
            Body += "<br><br>";
            Body += "Please recheck and proceed with the approval process.";
            Body += "<br>";



            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }


        public String RemoteITSVPApprovalRejection(RemoteAccessRequest request, bool isReject, bool EscalateToDCEO)
        {
            var statement = isReject == true ? "rejected" : "approved";
            
            String Body = EscalateToDCEO == true ? "<br><b>Dear DCEO,</b><br><br>" : "<br><b>Dear Network Implementer,</b><br><br>";

           
            Body += "The Remote Work Request - " + request.RemoteAccessRequestId + " has been " +statement+ ".";

            Body += "<br>";
            Body += "<br>";
            Body += "<b>Requester </b>: " + request.RequestedUser.FullName;
            Body += "<br>";
            Body += "<b>Access Type </b>: " + request.RemoteAccessType.EnumDisplayName();
           

           

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }

        public String RemoteDCEOApprovalRejection(RemoteAccessRequest request, bool isReject)
        {
            var statement = isReject == true ? "rejected" : "approved";

            String Body = "<br><b>Dear Network Implementer,</b><br><br>";

            Body += "The Remote Work Request - "+ request.RemoteAccessRequestId + " has been "+statement+".";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Requester </b>: " + request.RequestedUser.FullName;
            Body += "<br>";
            Body += "<b>Access Type </b>: " + request.RemoteAccessType.EnumDisplayName();


        

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }


        #endregion


        #region Asset Assigned

        // email sent when a new asset is assigned

        public String InitialAssetAssignedReminder(DateTime assignedDate, string name, Asset item)
        {
            String Body;

            Body = "<br><b>Dear " + name + ",</b><br><br>";
            Body += "This is a reminder that the IT asset " + item.AssetId + " assigned to you on " + assignedDate + " has not yet been accepted in the system.";
            Body += "<br>";
            Body += "<br>";
            Body += "If the asset is not accepted within <b>2 working days from today,</b> it will be <b>automatically assigned to you</b> as per IT Asset Management policy.";
            Body += "<br>";
            Body += "<br>";
            Body += "<b>Asset ID </b>: " + item.AssetId;
            Body += "<br>";
            Body += "<b>Asset Type </b>: " + item.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Assigned Date </b>: " + assignedDate;
           
            Body += "<br>";
            Body += "<br>";
            Body += "Please log in to the ITSM system and complete the acceptance process.";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }

        public String FinalAssetAssignedReminder(DateTime assignedDate, string name, Asset item)
        {
            String Body;

            Body = "<br><b>Dear " + name + ",</b><br><br>";
            Body += "This is to inform you that the IT asset " + item.AssetId + " <b>automatically assigned to you,</b> as acceptance was not completed within the stipulated time, despite previous reminders. ";
            Body += "<br>";
            Body += "<br>";                     
            Body += "<b>Asset ID </b>: " + item.AssetId;
            Body += "<br>";
            Body += "<b>Asset Type </b>: " + item.AssetType.AssetTypeName;
            Body += "<br>";
            Body += "<b>Assigned Date </b>: " + assignedDate;
           
            Body += "<br>";
            Body += "<br>";
            Body += "Please consider this email as the final notification regarding the asset assignment. ";

            Body += "<br><br>Regards,<br>";
            Body += "<b>ITSM System Notification</b>";

            return Body;
        }


        #endregion

    }
}